# Generated by Django 4.2.1 on 2023-08-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0006_chargepoint_hw_imsi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargepoint",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ConnectorLockFailure", "ConnectorLockFailure"),
                    ("EVCommunicationError", "EVCommunicationError"),
                    ("GroundFailure", "GroundFailure"),
                    ("HighTemperature", "HighTemperature"),
                    ("InternalError", "InternalError"),
                    ("LocalListConflict", "LocalListConflict"),
                    ("NoError", "NoError"),
                    ("OtherError", "OtherError"),
                    ("OverCurrentFailure", "OverCurrentFailure"),
                    ("OverVoltage", "OverVoltage"),
                    ("PowerMeterFailure", "PowerMeterFailure"),
                    ("PowerSwitchFailure", "PowerSwitchFailure"),
                    ("ReaderFailure", "ReaderFailure"),
                    ("ResetFailure", "ResetFailure"),
                    ("UnderVoltage", "UnderVoltage"),
                    ("WeakSignal", "WeakSignal"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
